services:
  flask:
    depends_on:
      - redis
    restart: unless-stopped
    env_file:
      - .env
    build: "."
    environment:
      - CACHE_TYPE=RedisCache
      - CACHE_REDIS_HOST=redis
      - CACHE_REDIS_PORT=6379
      - CACHE_REDIS_DB=0
    volumes:
      - "./.cache/fixtube:/root/.cache:cached"
    ports:
      - "5000:5000"

  redis:
    image: redis
    volumes:
      - "./.cache/redis:/data:cached"
    ports:
      - "6379:6379"
